### ISSUE TITLE
Bottom sheet covers entire screen on landscape view

### ISSUE THREAD

**Issue by jeffvg** [pxblue/complex-bottomsheet#1]
#### Bug or feature request?
Enhancement
#### What is the expected behavior?
Bottom sheet to include sticky close button/link
#### What is the current behavior?
Bottom sheet currently covers entire screen on landscape view, user will need to scroll to touch/click close button
#### What are the steps to reproduce?
1.  Open complex bottom sheet on any device or simulate in browser then open bottom sheet

#### What is your environment?

 Framework
- [X] Angular
- [X] React

 Browser
- [ ] Internet Explorer
- [ ] Safari
- [X] Chrome
- [ ] Firefox

 Operating System
- [ ] MacOS
- [ ] Windows
- [ ] Other

**Comment by daileytj** [comment]
Closing as this bug has been migrated to the angular-design-pattern monorepo.https://github.com/pxblue/angular-design-patterns/issues/30
